<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.6" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.6" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.6" />
    <PackageReference Include="QRCode.Avalonia" Version="1.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.6" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EvoConnect.Common\EvoConnect.Common.csproj" />
        <ProjectReference Include="..\EvoConnect.Server\EvoConnect.Server.csproj"/>
  </ItemGroup>
    <Target Name="CopyServerExecutable" AfterTargets="Build" Condition="&apos;$(Configuration)&apos; == &apos;Release&apos;">
    <ItemGroup>
      <ServerFiles Include="$(OutputPath)\..\EvoConnect.Server\**\*.*"/>
    </ItemGroup>
    <Copy SourceFiles="@(ServerFiles)" DestinationFolder="$(OutputPath)"/>
  </Target>
</Project>
