EXECUTE BLOCK
AS
  DECLARE VARIABLE v_count INTEGER;
BEGIN
  -- Index 1: IDX_PERSONNE_TYPE
  SELECT COUNT(*) FROM RDB$INDICES 
  WHERE RDB$INDEX_NAME = 'IDX_PERSONNE_TYPE'
  INTO :v_count;
  
  IF (v_count = 0) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_PERSONNE_TYPE ON PERSONNE(PER_TYPE)';

  -- Index 2: IDX_PLAN_PATIENT_DATE
  SELECT COUNT(*) FROM RDB$INDICES 
  WHERE RDB$INDEX_NAME = 'IDX_PLAN_PATIENT_DATE'
  INTO :v_count;
  
  IF (v_count = 0) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_PLAN_PATIENT_DATE ON PLAN_APPLIQUE(ID_PATIENT, DATE_RENS)';

  -- Index 3: IDX_PLAN_PATIENT_AMOUNT
  SELECT COUNT(*) FROM RDB$INDICES 
  WHERE RDB$INDEX_NAME = 'IDX_PLAN_PATIENT_AMOUNT'
  INTO :v_count;
  
  IF (v_count = 0) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_PLAN_PATIENT_AMOUNT ON PLAN_APPLIQUE(ID_PATIENT, MONTANT_EURO)';

  -- Index 4: IDX_RDV_PERSONNE
  SELECT COUNT(*) FROM RDB$INDICES 
  WHERE RDB$INDEX_NAME = 'IDX_RDV_PERSONNE'
  INTO :v_count;
  
  IF (v_count = 0) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_RDV_PERSONNE ON RENDEZ_VOUS(ID_PERSONNE, RDV_DATE)';

  -- Index 5: IDX_RDV_STATUT
  SELECT COUNT(*) FROM RDB$INDICES 
  WHERE RDB$INDEX_NAME = 'IDX_RDV_STATUT'
  INTO :v_count;
  
  IF (v_count = 0) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_RDV_STATUT ON RENDEZ_VOUS(RDV_STATUT, ID_PERSONNE)';

  -- Index 6: IDX_RDV_DATE_DESC
  SELECT COUNT(*) FROM RDB$INDICES 
  WHERE RDB$INDEX_NAME = 'IDX_RDV_DATE_DESC'
  INTO :v_count;
  
  IF (v_count = 0) THEN
    EXECUTE STATEMENT 'CREATE DESCENDING INDEX IDX_RDV_DATE_DESC ON RENDEZ_VOUS(RDV_DATE)';

  -- Index 7: IDX_PLAN_DATE_RENS
  SELECT COUNT(*) FROM RDB$INDICES 
  WHERE RDB$INDEX_NAME = 'IDX_PLAN_DATE_RENS'
  INTO :v_count;
  
  IF (v_count = 0) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_PLAN_DATE_RENS ON PLAN_APPLIQUE(DATE_RENS)';
END