EXECUTE BLOCK AS
BEGIN
  -- TABLE: VIP_PATIENT_STATS
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'VIP_PATIENT_STATS')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE VIP_PATIENT_STATS (
        ID INTEGER NOT NULL,
        ID_PERSONNE INTEGER NOT NULL,
        NOM VARCHAR(30),
        PRENOM VARCHAR(100),
        CA_GLOBAL DECIMAL(18,2) DEFAULT 0,
        CA_ANNUEL DECIMAL(18,2) DEFAULT 0,
        DERNIERE_VISITE TIMESTAMP,
        MOIS_DEPUIS_DERNIERE_VISITE INTEGER,
        STATUT VARCHAR(20),
        SORT_ORDER INTEGER,
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT PK_VIP_PATIENT_STATS PRIMARY KEY (ID),
        CONSTRAINT UK_VIP_PATIENT_PERSONNE UNIQUE (ID_PERSONNE)
      )' WITH AUTONOMOUS TRANSACTION;
  END

  -- SEQUENCE
  IF (NOT EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'SEQ_VIP_PATIENT_STATS')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_VIP_PATIENT_STATS' WITH AUTONOMOUS TRANSACTION;
  END

  -- TRIGGER: Before Insert
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'TRG_VIP_STATS_BI')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TRIGGER TRG_VIP_STATS_BI FOR VIP_PATIENT_STATS
      ACTIVE BEFORE INSERT POSITION 0
      AS
      BEGIN
        IF (NEW.ID IS NULL) THEN 
          NEW.ID = NEXT VALUE FOR SEQ_VIP_PATIENT_STATS;
        NEW.LAST_UPDATED = CURRENT_TIMESTAMP;
      END' WITH AUTONOMOUS TRANSACTION;
  END

  -- TRIGGER: Before Update
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'TRG_VIP_STATS_BU')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TRIGGER TRG_VIP_STATS_BU FOR VIP_PATIENT_STATS
      ACTIVE BEFORE UPDATE POSITION 0
      AS
      BEGIN
        NEW.LAST_UPDATED = CURRENT_TIMESTAMP;
      END' WITH AUTONOMOUS TRANSACTION;
  END

  -- INDEXES
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_VIP_STATS_STATUT')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_VIP_STATS_STATUT ON VIP_PATIENT_STATS(STATUT)' WITH AUTONOMOUS TRANSACTION;
  END

  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_VIP_STATS_CA_ANNUEL')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE DESCENDING INDEX IDX_VIP_STATS_CA_ANNUEL ON VIP_PATIENT_STATS(CA_ANNUEL)' WITH AUTONOMOUS TRANSACTION;
  END

  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_VIP_STATS_SORT')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_VIP_STATS_SORT ON VIP_PATIENT_STATS(SORT_ORDER, CA_ANNUEL)' WITH AUTONOMOUS TRANSACTION;
  END

  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_VIP_STATS_PERSONNE')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_VIP_STATS_PERSONNE ON VIP_PATIENT_STATS(ID_PERSONNE)' WITH AUTONOMOUS TRANSACTION;
  END

  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_VIP_STATS_DERNIERE_VISITE')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_VIP_STATS_DERNIERE_VISITE ON VIP_PATIENT_STATS(DERNIERE_VISITE)' WITH AUTONOMOUS TRANSACTION;
  END
END