EXECUTE BLOCK AS
BEGIN
  -- TABLE
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'KPI_CONFIG')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE KPI_CONFIG (
        ID INTEGER NOT NULL,
        KPI_CODE VARCHAR(50) NOT NULL,
        KPI_NAME VARCHAR(100) NOT NULL,
        KPI_ICON VARCHAR(10),
        TARGET_VALUE DECIMAL(10,2),
        UNIT VARCHAR(20),
        IS_ENABLED SMALLINT DEFAULT 1,
        WARNING_THRESHOLD DECIMAL(10,2),
        CRITICAL_THRESHOLD DECIMAL(10,2),
        DESCRIPTION VARCHAR(255),
        DISPLAY_ORDER INTEGER,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT PK_KPI_CONFIG PRIMARY KEY (ID),
        CONSTRAINT UK_KPI_CODE UNIQUE (KPI_CODE)
      )' WITH AUTONOMOUS TRANSACTION;
  END

  -- SEQUENCE
  IF (NOT EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'SEQ_KPI_CONFIG')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_KPI_CONFIG' WITH AUTONOMOUS TRANSACTION;
  END

  -- TRIGGERS
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'TRG_KPI_CONFIG_BI')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TRIGGER TRG_KPI_CONFIG_BI FOR KPI_CONFIG
      ACTIVE BEFORE INSERT POSITION 0
      AS
      BEGIN
        IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_KPI_CONFIG;
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
        NEW.UPDATED_AT = CURRENT_TIMESTAMP;
      END' WITH AUTONOMOUS TRANSACTION;
  END

  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'TRG_KPI_CONFIG_BU')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TRIGGER TRG_KPI_CONFIG_BU FOR KPI_CONFIG
      ACTIVE BEFORE UPDATE POSITION 0
      AS
      BEGIN
        NEW.UPDATED_AT = CURRENT_TIMESTAMP;
      END' WITH AUTONOMOUS TRANSACTION;
  END

  -- INDEXES
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_KPI_ENABLED')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_KPI_ENABLED ON KPI_CONFIG (IS_ENABLED)' WITH AUTONOMOUS TRANSACTION;
  END

  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_KPI_ORDER')) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_KPI_ORDER ON KPI_CONFIG (DISPLAY_ORDER)' WITH AUTONOMOUS TRANSACTION;
  END
END